### PR TITLE
Added export feature

### PR DESCRIPTION
**Pull request by theko2fi**
This pull request is aimed at enabling users to export a certificate in either **PEM** or **DER** format. Previously, there was no mechanism to retrieve an uploaded certificate, and I have encountered a situation where the original certificate file was lost.

Please refer to the attached demo video for more details:

https://github.com/strongswan/strongMan/assets/72862222/48f01d71-46a4-470e-96f8-a9fc3ca01602

### CODE REVIEW

**Comment by theko2fi** [comment]
Thanks for your feedback, I already emailed the maintainers to express my willingness to sign the Contributor License Agreement.

**Comment by tobiasbrunner** [comment]
@cla-bot check

Thanks again. I feel like this could be simplified quite a bit (and the third-party script/CSS could also be avoided) by just providing a single format and button. PEM should be enough I think.

**Comment by theko2fi** [comment]
@tobiasbrunner I've implemented the changes as suggested. The process has been simplified. Feel free to check it out, and let me know if you have any further thoughts.

**Comment by tobiasbrunner** [comment]
Thanks for the update. I've squashed your changed and pushed them with some changes to master. I've reformatted some stuff (code and HTML) and added support to export VICI certificates and handle names that contain e.g. spaces better.

**Pull request closed without merging**
